# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b769752568f2bd63bb97c71fd1215e23faa399a00c51189955d10d39f4f837734e708e8a85e8f478c59af0373935ab8c22ecf43fe9323da6477095f98735b7d

test:
  secret_key_base: 3039efc0b11399124e2aa62bc2809d7b36ef09ef63bc07743f0069a5a43a892978268797567c9fdb5b5a6b7074ce2e840cbc863e6873b6c2140e75a14a6fe5e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
